### ISSUE TITLE
Add 172.23.0.0/16, 172.24.0.0/14 to the reserved IPs as these are used by harbor internal bridges

### ISSUE THREAD

**Issue by rm75** [pivotal-cf/docs-pks#1024]
https://github.com/pivotal-cf/docs-pks/blob/1.6/nsxt-prepare-env.html.md.erb

Please add the following subnets to the reserved IPs as these are used by harbor internal bridges .

routing table of harbor VM's 
172.23.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-7c8dd3a35a3e
172.24.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-ab126cd1a8f4
172.25.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-3ffa76da051b
172.26.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-ff97768c5f9a
172.27.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-c97d556781a3

**Comment by pspinrad** [comment]
@lparis does this mean we should paste in the following to the bullet list here?
https://github.com/pivotal-cf/docs-pks/blob/1.6/nsxt-prepare-env.html.md.erb#L107

https://docs.pivotal.io/pks/1-6/nsxt-prepare-env.html#reserved-ip-blocks

```
  * 172.23.0.0/16
  * 172.24.0.0/16
  * 172.25.0.0/16
  * 172.26.0.0/16
  * 172.27.0.0/16
```

Thanks!

**Comment by lparis** [comment]
Yes, that is what it means. It looks like Harbor has expanded the IPs it uses, because this list was complete for a long time. We need to find out what version of Harbor this is in reference to. I suspect it is v9 or 10. https://docs.pivotal.io/partners/vmware-harbor/release-notes.html. Please check with rm75. We may need to follow up with Stuart or the Harbor PM Michael Michael. Thanks.

**Comment by lparis** [comment]
@pspinrad What is the status of this? Can we make the changes please and push them out? Thanks.

**Comment by pspinrad** [comment]
Never closed the loop here, but changes made:
https://docs.pivotal.io/pks/1-6/nsxt-prepare-env.html#reserved-ip-blocks
