### ISSUE TITLE
Improve workflow for adding a new Pod IP Block to an existing cluster using update-cluster

### ISSUE THREAD

**Issue by lparis** [pivotal-cf/docs-pks#1174]
See discussions here https://vmware.slack.com/archives/C8DJ383EX/p1596052407345900 and here https://vmware.slack.com/archives/C8DJ383EX/p1596052746346400?thread_ts=1596052407.345900&cid=C8DJ383EX. Probably need to create a single update-cluster topic replacing these topics: https://docs.pivotal.io/tkgi/1-8/network-profiles.html#update-profile and https://docs.pivotal.io/tkgi/1-8/network-profiles-define.html#change-pod-ips.

**Comment by pspinrad** [comment]
@lparis makes sense to add a new use case for "if you run out of IP addresses..."  but instead of replacing that section on updating a cluster's network profile, how about just leaving it there, as a general reference?  Referring to https://docs.pivotal.io/tkgi/1-8/network-profiles.html#update-profile   There are probably other reasons to update  an existing cluster's network profile.

If so, I'm thinking we should include or link to that section Limitation: Pod IP Block Changes https://docs.pivotal.io/tkgi/1-8/network-profiles-define.html#change-pod-ips in both the general instrux and the specific New IP Block use case.

**Comment by lparis** [comment]
https://github.com/pivotal-cf/docs-pks/pull/1196
