### ISSUE TITLE
GCP Firewall rule documentation isn't effective

### ISSUE THREAD

**Issue by bstick12** [pivotal-cf/docs-pks#190]
Under Installing and Configuring PKS on GCP -> Create a Firewall Rule for the Load Balancer we recommended that a Target tag of `pks-api` is assigned to the rule. This tag isn't assigned to the PKS VM so the firewall rule will never route correctly. 

A unique value that is generated by Ops Manager during tile installation is assigned to the VM as a tag. This is the product uuid from Ops Manager. That might be a better value to assign to the tag.

**Comment by bstick12** [comment]
@mjgutermuth The issue we discussed on Friday

**Comment by jaimegag** [comment]
@bstick12 I have always found `pks-api` added automatically as a network task of the PKS API VM in all my tests, and that's what I've been using all along, and so suggested it in the cookbook and to @mjgutermuth
Tested it last time with `v1.0.2`. Has this changed after?

**Comment by bstick12** [comment]
@jaimegag I did a deployment the other day and the tag wasn't added. The tag value seems a little generic. Wouldn't really allow the deployment of multiple PKS servers into the same VPC network in GCP.

**Comment by jaimegag** [comment]
@bstick12 Interesting. I'll re-test to see if I experience anything different. Anyhow, my recommendation was always to check if the network tag exists in the first place and add it otherwise.
Regarding allowing multiple PKS in the same VPC network, that is be possible with only one (simple) tag and one single FW rule. In fact some may choose to enable traffic to multiple PKS APIs with one single tag. You can choose to have different ones and different FW rules. I think it will really depend on how you want to go about it.

**Comment by kdolor-pivotal** [comment]
@jaimegag Were you able to re-test this?

**Comment by jaimegag** [comment]
@kdolor-pivotal I haven't tested from scratch to validate yet if the `pks-api` network tag or a similar is added by default or not.
Still, my recommendation and what's in the cookbook is to check if it is there and add it otherwise. 
My opinion about making this network tag generic (`pks-api`) vs more specific is that it making it generic still allow you to have multiple PKS deployments in the same VPC, as long as they are managed by a single Firewall rule. This might be ok for some people and it might not be for others. I find it subjective. But if people find `pks-api` too generic maybe we can suggest something that suggests it should be different per pks deployment (e.g: `pks-01-api` ?).

**Comment by mjgutermuth** [comment]
@bstick12 @jaimegag I think we can document both ways -- assigning a specific tag like `pks-01-api` or using the product UUID tag assigned by Ops Manager -- but we should present one as the default. Which is the more straightforward experience for the majority of PKS users?

**Comment by bstick12** [comment]
@mjgutermuth I think the `product-uuid` is preferable as this allows multiple deployments in the same project. Using `pks-01-api` will only work for a single deployment and is a little generic for larger environments.

**Comment by jaimegag** [comment]
@bstick12 You can have one single FW rule applicable for several deployments, as long as the PKS VM of each of those deployments have the same network tag. So it is really a choice.
A single FW rule with target tag `pks-api` could apply to as many VMs as you want as long as each VM has the same network tag applied. In GCP Iit is not a route, just an allow/deny rule.
If you want to be specific, you also can. If you use `product-uuid` then you need on FW rule per PKS VM. Same as if you use `pks-XY-api` (`pks-01-api`, `pks-02-api`, `pks-03-api`, etc). 1:1 relationship, same thing, different value.

**Comment by bstick12** [comment]
@jaimegag My misunderstanding. If that is the case then a still named tag works for me.

**Comment by mjgutermuth** [comment]
Thank you both! I've added a step to the PKS API load balancer config to make sure the tag exists, and if not, to add it.
