### ISSUE TITLE
Director Hostname

### ISSUE THREAD

**Issue by jerryhwg** [pivotal-cf/docs-pks#293]
In the doc, https://docs.pivotal.io/runtimes/pks/1-1/vsphere-om-config.html#dir-config

16. Leave the Director Hostname field blank.

Is this mandatory?

With it, you can't bosh cli to bosh director on NAT topology with NSX-T from external.

**Comment by bentarnoff** [comment]
Thanks for the headsup, @jerryhwang72! @lparis do you have any context on this? It appears to involve NSX-T on PKS.

**Comment by jerryhwang72** [comment]
@bentarnoff right it typically happens when bosh director (with a private ip) behind NAT (NSX-T Edge) so the hostname needs to be used to access bosh director via NAT.
A major problem I also found is if you set the hostname later, and apply the change, the bosh director is recreated and it loses all its communication with existing VMs so all the VMs need to be recreated.
So the hostname is better to be created during the install deployment if the feature is supposed to work, but the current doc mentions leave it blank so it's confusing.

**Comment by lparis** [comment]
See https://github.com/pivotal-cf/docs-pks/pull/456

**Comment by animatedmax** [comment]
Addressed by https://github.com/pivotal-cf/docs-pks/pull/456/files
