### ISSUE TITLE
Issue with the Canary Instances and max_in_flight

### ISSUE THREAD

**Issue by outofmem0ry** [pivotal-cf/docs-pks#358]
Issue with the `Canary Instances and max_in_flight` section under - https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/understanding-upgrades.html. Currently, the documentation states that max in flight impacts upgrade which is not the case. It impacts only cluster creation and resizes.

@carlo-colombo - From our slack conversation earlier.

**Comment by bentarnoff** [comment]
Thanks, @outofmem0ry. Could you be more specific about the changes you'd like to see in the documentation? For instance, would the following revised language be more accurate?

>The `max_in_flight` variable limits how many instances of a component can restart simultaneously when a cluster is created or resized.
This variable defaults to `1` and can be configured in the **PKS API** tab of the PKS tile.
Because the value is set to `1`, only one component restarts at a time.

Also, because this topic is specific to upgrading PKS, and `max_in_flight` does not affect upgrades, maybe we should remove the information about `max_in_flight` from this topic and place it somewhere else?

**Comment by carlo-colombo** [comment]
The description in the docs it's generic to bosh and not specific to pks, our implementation make tha parameter only working for cluster creation and resizing, while for upgrade we want rolling upgrade. Also PKS does not allow to configure the canary value of deployed clusters and it's alway equal to 1. 

I think that the actions (creation and resize) when the max in flight is taken in consideration should be added to the description of the field https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/installing-pks-gcp.html#pks-api

**Comment by outofmem0ry** [comment]
@bentarnoff You have touched upon a good point here. It makes sense to remove it from the upgrade section and add it to the link Carlo pointed to.
