### ISSUE TITLE
Feedback and issues with Managing Users in PKS with UAA section in our docs

### ISSUE THREAD

**Issue by outofmem0ry** [pivotal-cf/docs-pks#364]
- After enabling `UAA as OIDC provider` the note mentions

```
In order for cluster admins to grant cluster access to Kubernetes end users, cluster 
admins must ensure that they have selected Enable UAA as OIDC provider
in the UAA section of the PKS tile. Once you enable OIDC, you must run
get-credentials again to update your existing kubeconfig.

```
For cluster admins that have upgraded their clusters,  running `pks get-credentials` is not enough. They will also need to generate their own kubeconfig by following steps mentioned [here](https://github.com/pivotal-cf/docs-pks/blob/master/manage-users.html.md.erb#L311-#L335). This needs to be specifically called out in the documentation.

[Grant Cluster Access](https://docs-pcf-staging.cfapps.io/runtimes/pks/1-2/manage-users.html#cluster-access)
- This starts with a diagram depicting a three persona workflow. From the diagram, it looks like this section is only for LDAP users, which is not true. There should be a parallel track in the diagram showing the workflow for users utilizing internal uaa as OIDC provider.
- To configure properties mentioned [here] more examples should be provided with a sample kubeconfig. Currently, for a user new to OIDC changes it can be challenging to place these properties in a JSON context without examples.

**Comment by carlo-colombo** [comment]
@outofmem0ry 

* Do you mean to link from the first part of the documentation to the part where naomis flow is describe? In every case for Codys and Naomis calling `get-credentials` again is enough (and required) to get access back to the cluster. Codys then need to follow the documentation at the link you added for generating a kubeconfig for Naomi.
* _The following diagram outlines the workflow you use to grant cluster access to a user who belongs to an LDAP group:_  Due to a limitation in UAA LDAP is required to use groups in OIDC. It's possible to give access to single naomis to the cluster using cluster role binding but we expect the use case of groups for the customers and most of the user using always LDAP as identity provider for UAA. Maybe it make sense to move the chart to another location or make it more generic.
  * _Grant Cluster Access to a User_ section is valid for both UAA and UAA+LDAP installation
  * _Grant Cluster Access to a Group_ is instead only dedicated to UAA+LDAP installation (due to UAA limitation)
* I am not sure how much detail we need to get into kubernetes specific documentation, everything is available and updated at the link in the docs to k8s docs _For more information, see RoleBinding and ClusterRoleBinding in the Kubernetes documentation._

**Comment by bentarnoff** [comment]
@outofmem0ry I'm closing this issue because I believe these items have been addressed. Thanks.
