### ISSUE TITLE
Step 5 of OM Deploy Unnecessary

### ISSUE THREAD

**Issue by mcowger** [pivotal-cf/docs-pks#382]
Step 5 of the OM Deploy (https://docs.pivotal.io/runtimes/pks/1-2/aws-om-deploy.html#download) has instructions about creating an NS record, but terraform creates that record on its own in the cvustomers environment and mine as well.  I believe this step may not be necessary.

**Comment by kkallday** [comment]
Hi @mcowger. You are right, you provide the `zone_id` of your Route53 zone and `terraforming-aws` will create the `A` record for your Opsman in the zone that hosts your DNS.

Its interesting because this _assumes_ that your DNS is hosted in AWS. If you host your DNS elsewhere you wouldn't be able to use the `terraforming-aws` templates.

In `terraforming-gcp` the situation is different. It creates a DNS zone for you. Then you go to where your zone is hosted, create a NS record that points to the NS records that `terraforming-gcp` created (provided via outputs).

I'll let CF Infrastructure (maintainers) know about this inconsistency.

**Comment by kdolor-pivotal** [comment]
Hi @mcowger -- this has been amended in "Deploying Ops Manager on AWS"

Thanks!
