### ISSUE TITLE
Create AWS Load Balancer is in wrong order

### ISSUE THREAD

**Issue by mcowger** [pivotal-cf/docs-pks#385]
https://docs.pivotal.io/runtimes/pks/1-2/aws-api-load-balancer.html

As of step 5, there ISNT yet a pivotal container service EC2 instance, because installing PKS tile happens in the next step....there's nothing to add here.   Same problem for Step 8

**Comment by bentarnoff** [comment]
Hey @mcowger thanks so much for this feedback.

We've made the following changes:

1. We've moved the "Step 5: Add EC2 Instances" section from the "Creating an AWS Load Balancer for the PKS API" topic to the "Installing PKS on AWS" topic: https://docs.pivotal.io/runtimes/pks/1-2/installing-pks-aws.html.

2. Since ["Step 8: Register the PKS API FQDN"](https://docs.pivotal.io/runtimes/pks/1-2/aws-api-load-balancer.html#register-fqdn) is not required when using Terraform scripts, we will plan to delete it. (Because currently, we don't document a way to deploy PKS on AWS that *doesn't* use Terraform.) We will also need to tell the user how they will retrieve the FQDN that is being registered for them by Terraform, most likely somewhere in the ["Installing PKS on AWS"](https://docs.pivotal.io/runtimes/pks/1-2/installing-pks-aws.html) topic. We have created a story for this work in our Tracker (https://www.pivotaltracker.com/story/show/161800178), and have blocked it on the completion of the docs for the new PKS AWS Terraform templates, which we are hoping to complete this week with Customer0.

I'm closing this out for now, but please let us know if you have further feedback. Thanks again!
