### ISSUE TITLE
Resource Config - VM Type pulldown

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/docs-pks#552]
The image that shows the Resource config appears to refer to a vm type of "large", but since it is cut off, we cannot tell if that is "large-mem" or "large-disk".  We had an issue installing due to disk size, so I would like to make sure we show the vm type with its full spec - "automatic - large - cpu - disk(eph)" .  just can't see it in the image.

**Comment by mjgutermuth** [comment]
Thanks for calling this out, @agregory999! I'm not sure which IaaS you're using, but the exact words used in the "large" label do vary by IaaS. The "Automatic" value is intended to meet the minimum resource requirements. I added a table to the Resource Config step to make those minimum requirements more clear, for example: https://docs.pivotal.io/runtimes/pks/1-3/installing-pks-aws.html#resource-config

If you're finding that the "Automatic" value is not actually sufficient for the PKS VM, definitely follow up with someone on the product team so that they can adjust the minimum requirements. Thanks again!
