### ISSUE TITLE
Add FQDN to cert generation steps for NSX-T 2.4?

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal-cf/docs-pks#657]
The generate cert and keys steps in 
https://docs.vmware.com/en/VMware-Enterprise-PKS/1.4/vmware-enterprise-pks-14/GUID-generate-nsx-ca-cert-24.html don't included a FQDN for the NSX_MANAGER_COMMONNAME like was done previously for 2.3. Is this intended? 

If after checking with eng that it should include a FQDN, please update docs.

**Comment by lparis** [comment]
Keith, it is intended because we are using the VIP and in this case it has to be the VIP for the commonName. To use an FQDN, you will need to have a load balancer. We are working on the docs for that for 1.4.1. I am not sure who you checked with in Engineering, but you may want to check again. This is the quote from the networking engineer lead: "for cluster VIP to work, I guess you have to have cluster VIP as common name, because you register it as cluster ca cert, not node ca cert. the server response cert will come back with VIP in it. it has to be the common name."
