### ISSUE TITLE
ClusterRoleBinding sample in the PSP - subject[0].namespace missing

### ISSUE THREAD

**Issue by msathe-tech** [pivotal-cf/docs-pks#992]
Take a look at PSP docs to create Cluster Role Binding - 
https://docs.pivotal.io/pks/1-6/pod-security-policy.html#psp-binding

The namespace is missing and it errors out.

**Comment by ograves-pivotal** [comment]
Hello @msathe-tech.
Thanks. Ollie in Docs here. 

I need a little clarification from you to determine if this is only a documentation/clarification issue or if there is also a code issue that should be reported.

The kubernets docs state: "_...a ClusterRoleBinding may be used to grant permission at the cluster level and in all namespaces..._". 

So a ClusterRoleBinding configuration should not require namespace.

Reviewing this Pivotal Docs topic it describes configuring either a **RoleBinding** (with namespace), or **ClusterRoleBinding** cluster-wide configuration, but only shows an example for ClusterRoleBinding w/our namespace. 

Which were you attempting? Had you actually configured for **ClusterRoleBinding** when this error occurred?

Even without your answer I can see we also need to include in the Pivotal Docs either a complete RoleBinding example or a reminder to include the namespace property if changing the example to `kind: RoleBinding`. 

Let me know your thoughts. Thanks.

**Comment by msathe-tech** [comment]
There is a sample CRB in the docs -
name: psp:restricted

This one has missing namespace for the Subjects.

**Comment by ograves-pivotal** [comment]
Hi @msathe-tech 
Yes. The **ClusterRoleBinding** examples in that topic do NOT include `subjects`: `namespace` because the Kubernetes docs state it is not required. Since it is not officially required we do not include it in our docs.

If your **ClusterRoleBinding** PSP failed for you, and you fixed it by revising the configuration with `subjects`: `namespace` I must instead raise an issue with engineering.

Please confirm that this issue is not just a comment on the docs, but that you actually attempted to make a **ClusterRoleBinding** PSP and received an error. I know it's been a week, but if you have any supporting log(s) please also provide them so I can report the issue. 

Sorry to ask so many questions about a configuration property.

Thanks so much.

**Comment by ograves-pivotal** [comment]
Clarifications have been pushed into current PKS v1.6 and future versions
